apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
data:
  MONGODB_USER: {{ .Values.secrets.MONGODB_USER }}
  MONGODB_PASSWORD: {{ .Values.secrets.MONGODB_PASSWORD }}
