apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: grade-submission
spec:
  selector:
    app.kubernetes.io/instance: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017